listen_addr: ":8124"          # Address the proxy listens on
header_name: "X-User-Id"      # Header to group by
max_concurrent: 3             # Max simultaneous queries per X-User-Id
max_queue: 10                 # Max queued queries per X-User-Id
queue_timeout: 60s            # Max time to wait in queue
replicas:
  - "clickhouse-node1:8123"   # Your ClickHouse nodes
  - "clickhouse-node2:8123"
replica_scheme: "http"        # Or "https" if needed
# --- Slowdown Trigger ---
# Option 1: Specific error message substring
slowdown_error: "Too many simultaneous queries"
# Option 2: Specific status code (use one or both)
slowdown_code: 503 # Example: If ClickHouse returns 503 for this
# --- Slowdown Rate ---
slowdown_rate: 1.0            # Limit to 1 query/second when slowed down
slowdown_burst: 1             # Allow burst of 1

proxy_timeout: 120s           # Timeout for requests to backend replicas
user_agent: "SimpleClickHouseProxy/1.0"