name: chproxy
services:
  clickhouse-01:
    image: clickhouse/clickhouse-server:25.5.1
    container_name: clickhouse-01
    hostname: clickhouse-01
    ports:
      - "8123:8123" # HTTP port for node 1
      - "9000:9000" # Native TCP port for node 1
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - KEEPER_ID=1
    volumes:
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./docker/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./docker/clickhouse/enable_keeper.xml:/etc/clickhouse-server/config.d/enable_keeper.xml
      - ./docker/clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - clickhouse-01-data:/var/lib/clickhouse
      - clickhouse-01-logs:/var/log/clickhouse-server
    networks:
      chproxy:
        ipv4_address: 10.5.0.2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
#    depends_on:
#      - clickhouse-keeper
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  clickhouse-02:
    image: clickhouse/clickhouse-server:25.5.1
    container_name: clickhouse-02
    hostname: clickhouse-02
    ports:
      - "8124:8123" # HTTP port for node 2 (mapped to different host port)
      - "9001:9000" # Native TCP port for node 2 (mapped to different host port)
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - KEEPER_ID=2
    volumes:
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./docker/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./docker/clickhouse/enable_keeper.xml:/etc/clickhouse-server/config.d/enable_keeper.xml
      - ./docker/clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - clickhouse-02-data:/var/lib/clickhouse
      - clickhouse-02-logs:/var/log/clickhouse-server
    networks:
      chproxy:
        ipv4_address: 10.5.0.3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
#    depends_on:
#      - clickhouse-keeper
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  clickhouse-01-data:
  clickhouse-01-logs:
  clickhouse-02-data:
  clickhouse-02-logs:

networks:
  chproxy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
