version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181

  clickhouse-01:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-01
    hostname: clickhouse-01
    ports:
      - "8123:8123" # HTTP port for node 1
      - "9000:9000" # Native TCP port for node 1
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
    volumes:
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./docker/clickhouse/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      - ./docker/clickhouse/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - clickhouse-01-data:/var/lib/clickhouse
      - clickhouse-01-logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  clickhouse-02:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-02
    hostname: clickhouse-02
    ports:
      - "8124:8123" # HTTP port for node 2 (mapped to different host port)
      - "9001:9000" # Native TCP port for node 2 (mapped to different host port)
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
    volumes:
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./docker/clickhouse/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      - ./docker/clickhouse/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - clickhouse-02-data:/var/lib/clickhouse
      - clickhouse-02-logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  clickhouse-01-data:
  clickhouse-01-logs:
  clickhouse-02-data:
  clickhouse-02-logs:

networks:
  default:
    driver: bridge
